CREATE TABLE #TABELAA(IDA INT, QTDE INT )
CREATE TABLE #TABELAB(IDA INT, NOME NVARCHAR(30) )

INSERT INTO #TABELAA(IDA, QTDE) VALUES(1, 100),(2, 50),(3, 75)
INSERT INTO #TABELAB(IDA, NOME) VALUES(1, 'JOSÉ'),(2, 'MARIA'),(4, 'JOAQUIM'),(5,'JUREMA')

SELECT * FROM #TABELAA
SELECT * FROM #TABELAB

SELECT 'INNER JOIN' AS OPERAÇÃO, * FROM #TABELAA A INNER JOIN #TABELAB B ON A.IDA = B.IDA
UNION ALL SELECT 'LEFT JOIN (INCLUSIVO)', * FROM #TABELAA A LEFT JOIN #TABELAB B ON A.IDA = B.IDA
UNION ALL SELECT 'LEFT JOIN (EXCLUSIVO)', * FROM #TABELAA A LEFT JOIN #TABELAB B ON A.IDA = B.IDA  WHERE A.IDA IS NULL OR B.IDA IS NULL
UNION ALL SELECT 'RIGHT JOIN (INCLUSIVO)', * FROM #TABELAA A RIGHT JOIN #TABELAB B ON A.IDA = B.IDA
UNION ALL SELECT 'RIGHT JOIN (EXCLUSIVO)', * FROM #TABELAA A RIGHT JOIN #TABELAB B ON A.IDA = B.IDA WHERE A.IDA IS NULL OR B.IDA IS NULL
UNION ALL SELECT 'FULL OUTER JOIN (INCLUSIVO)', * FROM #TABELAA A FULL OUTER JOIN #TABELAB B ON A.IDA = B.IDA
UNION ALL SELECT 'FULL OUTER JOIN (EXCLUSIVO)', * FROM #TABELAA A FULL OUTER JOIN #TABELAB B ON A.IDA = B.IDA WHERE A.IDA IS NULL OR B.IDA IS NULL

DROP TABLE #TABELAA
DROP TABLE #TABELAB